# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Design 2B – Experimental Computing
email: nika@nikafisher.com
description: > # this means to ignore newlines until "baseurl:"
  Design 2B at Rutgers University. Spring 2019.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# Site nav
navigation:
  - Agenda: /agenda
  - Projects: /projects
  - Exercises: /lectures
  - Students: /students
  - Information: /info
  - Resources: /resources

# Custom collections
collections:
  projects:
    output: true
  readings:
  students:
  agendas:
    output: true
  lectures:
    output: true

# Collection Defaults
defaults:
  - scope:
      type: projects
    values:
      layout: project
      permalink: /:collection/:title
  - scope:
      type: agendas
    values:
      layout: agenda
      permalink: /:collection/:title
  - scope:
      type: lectures
    values:
      layout: lecture
      permalink: :collection/:path
